### ISSUE TITLE
doesnt scafold anything

### ISSUE THREAD

**Issue by Agathesev** [OwenMelbz/generator-jekyll-webapp#2]
everything in title

**Comment by OwenMelbz** [comment]
Just tried installing it on a system that has never used it before, and it seems to work fine.

Its not actually being actively supported/developed so if you cannot get it working, best bet is to find an alternative solution

**Comment by Agathesev** [comment]
My system is osx El Capitan, I've already use yeoman to scafold project. And closing this "issue" without more explainaition is no good job.

**Comment by Agathesev** [comment]
nevermind ! Got to find something else...
